# Generated by Django 5.2.17 on 2026-09-21 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='faculty.indexpage')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('BA', 'Бакалавр'), ('MA', 'Магістр'), ('SP', 'Спеціаліст'), ('CAND', 'Кандидат наук'), ('DR', 'Доктор наук'), ('PhD', 'Доктор філософії')], max_length=32)),
                ('position', models.CharField(choices=[('PROF', 'Професор'), ('DOC', 'Доцент'), ('SLEC', 'Старший викладач'), ('LEC', 'Викладач та асистент'), ('HEAD', 'Завідувач кафедри'), ('DEAN', 'Декан'), ('RECT', 'Ректор')], max_length=32)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.department')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.department')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.tutor')),
            ],
        ),
    ]
