# Generated by Django 5.2.17 on 2026-10-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('university', models.CharField(max_length=255)),
                ('languages', models.CharField(max_length=255)),
                ('places', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
